version: 2

jobs:
  build:
    working_directory: ~/virtualboombox

    docker:
      - image: circleci/python:3.6-stretch-node-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgres://circleci:@127.0.0.1:5432/virtualboombox_test
          REDIS_URL: redis://127.0.0.1:6379/0
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          - POSTGRES_USER=circleci
          - POSTGRES_DB=virtualboombox_test

    steps:
      - checkout

      - run:
          name: Installing System Dependencies
          command: sudo pip install poetry

      - run:
          name: Checking System Dependencies
          command: make doctor

      - type: cache-restore
        key: pipenv-{{ checksum "Pipfile.lock" }}

      - run:
          name: Installing Project Dependencies
          command: make install

      - type: cache-save
        key: pipenv-{{ checksum "Pipfile.lock" }}
        paths:
          - .venv

      - run:
          name: Checking Code
          command: make check

      - run:
          name: Running Tests
          command: make test
