# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, default=42.9634, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=85.6681, max_digits=9)),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='song',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=42.9634, max_digits=9),
        ),
        migrations.AlterField(
            model_name='song',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=85.6681, max_digits=9),
        ),
    ]
