# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20170129_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Account'),
        ),
    ]
