# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20170130_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youtube_url',
            field=models.URLField(default='https://www.youtube.com/v/dQw4w9WgXcQ'),
        ),
    ]
