# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_song_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_url',
            field=models.URLField(null=True),
        ),
    ]
