# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_account_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
