# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0008_account_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Song')),
            ],
        ),
    ]
